### ISSUE TITLE
Error Message on Scheduling Tool 

### ISSUE THREAD

**Issue by apatheticslacker** [CrisisTextLine/CTL-Online#11]
When I'm on a supervisor account with the scheduling tool, I got this error message when I select shift scheduling, I'm given this: 

![image](https://cloud.githubusercontent.com/assets/7773483/8366616/7df87b16-1b64-11e5-9bdc-5b7958c9472b.png)

Followed with: 

![image](https://cloud.githubusercontent.com/assets/7773483/8366652/b7f998ea-1b64-11e5-8650-6504da301c34.png)

Account Info: 

Username: apatheticslacker@gmail.com
pass: givesleepplease

**Comment by cjcodes** [comment]
Closing. Dev server. Lol testing things.
