### ISSUE TITLE
trainers should be allowed to see trainees' quiz results

### ISSUE THREAD

**Issue by icylace** [CrisisTextLine/CTL-Online#139]
Notes:

/my-trainees > a trainee from the list > my results tab for trainee > operations view > oops!
- The "oops!" page should be accessible by any trainer

- example:
  https://online.crisistextline.org/user/15465/quiz-results

https://online.crisistextline.org/admin/structure/views/view/quiz_user_results/edit/page

**Comment by icylace** [comment]
The view that controls the page that we want to allow trainers to access should be https://online.crisistextline.org/admin/structure/views/view/quiz_user_results/edit/page.

The problem is that for any given results page we need to allow access to trainers (and up), the trainee whose page it is, but to not allow access by other trainees.  The current permission used for the view is "View own quiz results" which ensures that other trainees don't have access but also prevents trainers from viewing too.  We cannot add another permission check to the view.  If we could, it would be "View any quiz results".  We are only allowed to have one permission for the view to check for.  Switching the permission check to "View any quiz results" I think would prevent any trainee from viewing the page, including the trainee whose page it is.  Also, allowing usage of the "View any quiz results" permission by changing it to include the authenticated user role would allow any trainee to see the results page which is what we don't want.

I recommend a different approach, namely by creating or modifying another view.

**Comment by cjcodes** [comment]
This was unrelated to the view. There was a permission problem where trainers couldn't see questions outside of a quiz itself. That permission has been enabled and trainers can now see what they need.
