### ISSUE TITLE
Invitation Bug

### ISSUE THREAD

**Issue by KaleyLeshem** [CrisisTextLine/CTL-Online#148]
Alan didn’t get invited to training but should have. Accepted + background passed. https://online.crisistextline.org/user/20235/edit 

Eight people, including Alan, who weren’t invited because they’re being assigned deferral dates without deferring. These are brand-new Accepted folks who’ve never been invited before.
![screen_shot_2015-12-23_at_1 10 43_pm_720](https://cloud.githubusercontent.com/assets/14890770/12118010/26f81ba2-b392-11e5-9532-8ff856e13f45.png)

**Comment by icylace** [comment]
From what URL and what time was that screenshot taken?  I checked the account you linked me to and Alan Metja has the "Deferred" role instead of "Accepted".  I also checked a random person from the list in the screenshot, Christine Nguyen, and she has the following roles instead of "Accepted":  "Beta", "Crisis Counselor I", "Graduate"

**Comment by KaleyLeshem** [comment]
The screenshot is from Dec 23rd at 1:11PM- unfortunately these roles had to
be changed to proceed with training. Will think about ways to replicate
this bug for next time we do registration.

On Tue, Jan 5, 2016 at 11:29 AM, Ron Martinez <notifications@github.com>
wrote:

> From what URL and what time was that screenshot taken? I checked the
> account you linked me to and Alan Metja has the "Deferred" role instead of
> "Accepted". I also checked a random person from the list in the screenshot,
> Christine Nguyen, and she has the following roles instead of "Accepted":
> "Beta", "Crisis Counselor I", "Graduate"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CrisisTextLine/CTL-Online/issues/148#issuecomment-169051304>
> .
>



-- 
Kaley Leshem
Head of Training Product Development
Crisis Text Line
Save lives with us—Apply to be a Crisis Counselor here
<http://crisistextline.org/volunteer>
(646) 693-3470 X 220
