### ISSUE TITLE
Office Hours Not in Logical Order 

### ISSUE THREAD

**Issue by apatheticslacker** [CrisisTextLine/CTL-Online#15]
Office Hours should be listed in a logical order (by date), but they are currently listed alphabetically, and this is causing some confusion for trainers and trainees

Relevant Screenshot: 
![screen_shot_2015-07-16_at_1 22 28_pm](https://cloud.githubusercontent.com/assets/7773483/8829835/d30a969a-3066-11e5-9a63-9dd5f849928a.png)

Trello Card: https://trello.com/c/6W64BH5S/75-office-hours-should-be-listed-in-a-logical-order-by-date-but-they-are-currently-listed-alphabetically

**Comment by icylace** [comment]
I updated the sorting for the Office Hours view.  It should work as expected now.
