### ISSUE TITLE
Reference duplicates for applicants 

### ISSUE THREAD

**Issue by KaleyLeshem** [CrisisTextLine/CTL-Online#154]
The system isn't catching when the an applicant has the same reference twice. This is heather's view. Both of the users below have only one reference. 
![screen_shot_2016-01-12_at_2 29 54_pm_720](https://cloud.githubusercontent.com/assets/14890770/12463676/057dae12-bf93-11e5-840b-83a0d7e21298.png)
![screen shot 2016-01-20 at 4 31 24 pm](https://cloud.githubusercontent.com/assets/14890770/12463732/53f2de5a-bf93-11e5-8254-825e653f95a7.png)

*Potential bandaid solution - changing Heather's view to display names of references instead of the #

**Comment by KaleyLeshem** [comment]
@cjcodes

**Comment by cjcodes** [comment]
Fixed by counting distinct(name) instead of distinct(nid)
