### ISSUE TITLE
Cannot Search Certain Trainers on Training Report

### ISSUE THREAD

**Issue by apatheticslacker** [CrisisTextLine/CTL-Online#19]
When searching for Kaley or Freddie on the training report, nothing shows up. This isn't an issue with other names when searched and using Freddie's former name Alysha. 

 Not an issue when I search other trainee names https://online.crisistextline.org/admin/training-report

How search results should work out: 
![screen_shot_2015-07-23_at_3 47 16_pm__2_](https://cloud.githubusercontent.com/assets/7773483/8860561/aebd7126-3152-11e5-8ef3-b19c68df3d5a.png)

What's coming out: 
![screen_shot_2015-07-23_at_3 39 11_pm__2_](https://cloud.githubusercontent.com/assets/7773483/8860574/c46dba1c-3152-11e5-9830-623b428cb8fe.png)

Relevant Trello Card: https://trello.com/c/3AArMjDp/52-training-report-when-i-search-kaley-or-freddie-nothing-shows-up-not-an-issue-when-i-search-other-trainee-names-https-online-cris

**Comment by icylace** [comment]
Actually, it turns out that Kaley's first name field in her user profile contains a trailing space which is why searching with her name on the course report page gives no results.  I have already asked Kaley to update her profile.
