### ISSUE TITLE
Profile Notes not Saving/Viewable

### ISSUE THREAD

**Issue by RamneetKS** [CrisisTextLine/CTL-Online#79]
Estimated # or % of affected users: All trainers, supervisors and some trainees
Email of one of the people affected: Cmiller@crisistextline.org
Screenshot (attach): attached.
Impact: Staff need to document any issues with trainees, failed final evaluations trainees etc. 
Steps to replicate
-- Who: CTL Online 
-- What: trainers adding notes in the profile but either its not saving or other trainers/staff can't see it
-- When: throughout training
-- Where: CTL Online User Profile
-- How:
![screen shot 2015-10-02 at 10 40 10 am](https://cloud.githubusercontent.com/assets/14890786/10312996/8246f55a-6c1b-11e5-946c-c2028e7df44a.png)

**Comment by icylace** [comment]
Profile notes are viewable/editable in the "Comments" section on the edit tab for user profiles (e.g. https://online.crisistextline.org/user/7822/edit)
