### ISSUE TITLE
Trainee Assignment Page Show V1 Applicants

### ISSUE THREAD

**Issue by RamneetKS** [CrisisTextLine/CTL-Online#85]
Estimated # or % of affected users: 1000+ trainees/applicants
Email of one of the people affected: 
Screenshot (attach): attached. 
Impact: Staff / Users
Steps to replicate
-- Who: Ctl online
-- What: Trainers/Admins use the "trainee assignment" view to identify trainer assignments, send sms in mass, mass assign trainers, cohort # and roles. 
-- When: 10/8/15
-- Where: People/search click "trainee assignment"
![screen shot 2015-10-06 at 12 08 43 pm](https://cloud.githubusercontent.com/assets/14890786/10377879/c12d3036-6dd3-11e5-95a4-84658266ff4f.png)

-- How: https://online.crisistextline.org/admin/people/search

**Comment by icylace** [comment]
I just updated the Trainee Assignment (https://online.crisistextline.org/admin/trainees) view while in a meeting with Kaley.  V2 applicants should show up as well now.
